### ISSUE TITLE
Add Review

### ISSUE THREAD

**Issue by Arsitur** [AAndrei06/Relax_website#35]
User-ul sa poata adauga review-uri, ai de facut sa se adauge in baza de date, tiam lasat in cod daca dai pull la menuItems linia // Salvare reviews in baza de date [Andrei], ca sa ajungi acolo doar apasa CTRL + F si da paste la linia si ajungi direct acolo, acolo este deja un review object tu doar trebuie sa il adaugi in baza de date @AAndrei06

**Comment by AAndrei06** [comment]
solved
