### ISSUE TITLE
Edit la pret

### ISSUE THREAD

**Issue by Arsitur** [AAndrei06/Relax_website#36]
Cand apesi pe un menu item tot mere bine (Editare, Adaugare, Stergere etc..), singurul lucru care nu mere e cand editezi pretul, asa editarea merge perfect, dar cand schimbi pretul itemul parca se sterge, n-am nici o idee de ce, mult noroc // Pret erroare [Andrei], linia 155 @AAndrei06

**Comment by AAndrei06** [comment]
Solved
